name: Package exe with PyInstaller - Windows
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          spec: 'instalock.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'InstaLock'
          options: --onefile, --name "InstaLock", --windowed, 